# Generated by Django 2.2.4 on 2020-04-16 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=40, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=40, verbose_name='district')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='district_of_area', to='myapp.Area', verbose_name='area')),
            ],
        ),
        migrations.CreateModel(
            name='CityOrVillage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_or_village', models.CharField(max_length=40, verbose_name='city or village')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city_of_district', to='myapp.District', verbose_name='district')),
            ],
        ),
    ]
