# Generated by Django 2.2.4 on 2020-04-16 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_area_cityorvillage_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name and Last Name')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('address', models.CharField(max_length=40, verbose_name='address')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('approved', 'Подтверждена')], default='new', max_length=20, verbose_name='status')),
                ('pregnancy', models.CharField(choices=[('yes', 'да'), ('no', 'нет')], default='no', max_length=20, verbose_name='pregnancy')),
                ('weeks_of_pregnancy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='number of weeks of pregnancy')),
                ('notes', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time of add')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='area_in_application', to='myapp.Area', verbose_name='Area')),
                ('city_or_village', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city_or_village_in_application', to='myapp.CityOrVillage', verbose_name='City or Village')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='district_in_application', to='myapp.District', verbose_name='District')),
            ],
        ),
    ]
