# Generated by Django 2.2.4 on 2020-04-16 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceProvided',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2000, verbose_name='Description')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date of add')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='assistance_provided',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assistance_provided_in_application', to='myapp.AssistanceProvided', verbose_name='assistance provided'),
        ),
    ]
