# Generated by Django 2.2.4 on 2020-04-16 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200416_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='assistance_provided',
        ),
        migrations.AddField(
            model_name='assistanceprovided',
            name='assistance_provided',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application_in_assistance_provided', to='myapp.Application', verbose_name='assistance provided'),
        ),
    ]
