# Generated by Django 2.2.4 on 2020-04-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200416_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistanceprovided',
            name='date',
            field=models.DateField(verbose_name='date of add'),
        ),
    ]
